# Visit https://goreleaser.com for documentation on how to customize this
# behavior.

version: 2

project_name: exec-pipeline
before:
  hooks:
    - go mod tidy
builds:
  - skip: true
archives:
  - formats: ['zip', 'tar.gz']
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
release:
  github:
    owner: librucha
    name: exec-pipeline
changelog:
  use: git
signs:
  - artifacts: all